name: Docker CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build test Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: test
          push: false
          tags: daggergm:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Run tests in Docker
        run: |
          docker run --rm daggergm:test npm run test:coverage

  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build test Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: test
          push: false
          tags: daggergm:lint
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Run linting in Docker
        run: |
          docker run --rm daggergm:lint npm run lint

      - name: Run type checking in Docker
        run: |
          docker run --rm daggergm:lint npm run typecheck